--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.1.31.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/6/2016 4:32:42 PM
-- Server version: 5.7.12-log
-- Client version: 4.1
--


--
-- Definition for database area72webdemo
--
DROP DATABASE IF EXISTS area72webdemo;
CREATE DATABASE area72webdemo
	CHARACTER SET utf8
	COLLATE utf8_general_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE area72webdemo;

--
-- Definition for table adminlevel
--
CREATE TABLE adminlevel (
  adminlevelid INT(11) NOT NULL AUTO_INCREMENT,
  adminlevelname VARCHAR(255) NOT NULL DEFAULT 'user',
  PRIMARY KEY (adminlevelid)
)
ENGINE = INNODB
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table areas
--
CREATE TABLE areas (
  areasindex INT(11) NOT NULL AUTO_INCREMENT,
  areaname VARCHAR(255) DEFAULT NULL,
  areadescription VARCHAR(255) DEFAULT NULL,
  updated TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updatedby INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (areasindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table committeepositions
--
CREATE TABLE committeepositions (
  committeepositionsindex INT(11) NOT NULL AUTO_INCREMENT,
  committeeindex INT(11) DEFAULT NULL,
  `position` VARCHAR(255) DEFAULT NULL,
  positiondescription VARCHAR(255) DEFAULT NULL,
  rotationindex INT(11) DEFAULT NULL,
  PRIMARY KEY (committeepositionsindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table committees
--
CREATE TABLE committees (
  committeesindex INT(11) NOT NULL AUTO_INCREMENT,
  committee VARCHAR(255) DEFAULT NULL,
  orglevelid INT(11) NOT NULL,
  committeedescription LONGTEXT DEFAULT NULL,
  committeechair INT(11) DEFAULT NULL COMMENT 'Comes from Member''s Table',
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updatedby INT(11) NOT NULL DEFAULT 1,
  areasindex INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (committeesindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 33
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table districts
--
CREATE TABLE districts (
  districtsindex INT(11) NOT NULL AUTO_INCREMENT,
  district VARCHAR(255) DEFAULT NULL,
  districtdescription VARCHAR(255) DEFAULT NULL,
  areaindex INT(11) DEFAULT 1,
  updated TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updatedby INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (districtsindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 43
AVG_ROW_LENGTH = 390
CHARACTER SET latin1
COLLATE latin1_swedish_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table districtzipcodes
--
CREATE TABLE districtzipcodes (
  districtzipcodesindex INT(11) NOT NULL AUTO_INCREMENT,
  zipcode INT(5) DEFAULT NULL,
  updated TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updatedby INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (districtzipcodesindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table groups
--
CREATE TABLE groups (
  groupsindex INT(11) NOT NULL AUTO_INCREMENT,
  groupname VARCHAR(255) DEFAULT NULL,
  districtindex INT(11) DEFAULT NULL,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updatedby INT(11) NOT NULL DEFAULT 1,
  gsonumber VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (groupsindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table gsrbygroup
--
CREATE TABLE gsrbygroup (
  gsrindex INT(11) NOT NULL AUTO_INCREMENT,
  memberid INT(11) NOT NULL,
  groupid INT(11) NOT NULL,
  rotationbegin DATETIME DEFAULT NULL,
  rotationend DATE DEFAULT NULL,
  Comments LONGTEXT DEFAULT NULL,
  PRIMARY KEY (gsrindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table locationcomments
--
CREATE TABLE locationcomments (
  locationcommentsindex INT(11) NOT NULL AUTO_INCREMENT,
  locationid INT(11) DEFAULT NULL,
  details VARCHAR(25) NOT NULL,
  private BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (locationcommentsindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table locationdetails
--
CREATE TABLE locationdetails (
  locationdetailsindex INT(11) NOT NULL AUTO_INCREMENT,
  locationsindex INT(11) NOT NULL,
  LocationDetails VARCHAR(255) DEFAULT NULL,
  updated TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updatedby INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (locationdetailsindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table locations
--
CREATE TABLE locations (
  locationsindex INT(11) NOT NULL AUTO_INCREMENT,
  locationname VARCHAR(255) DEFAULT NULL,
  locationaddress VARCHAR(255) DEFAULT NULL,
  locationcity VARCHAR(255) DEFAULT NULL,
  locationstate VARCHAR(2) NOT NULL DEFAULT 'WA',
  locationzip INT(5) NOT NULL DEFAULT 0,
  locationtypeid INT(11) DEFAULT NULL,
  locationlat FLOAT(10, 6) DEFAULT NULL,
  locationlng FLOAT(10, 6) DEFAULT NULL,
  updated TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updatedby INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (locationsindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table locationtypes
--
CREATE TABLE locationtypes (
  locationtypesindex INT(11) NOT NULL AUTO_INCREMENT,
  locationtype VARCHAR(255) DEFAULT NULL,
  updated TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updatedby INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (locationtypesindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 9
AVG_ROW_LENGTH = 2048
CHARACTER SET latin1
COLLATE latin1_swedish_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table meetingchanges
--
CREATE TABLE meetingchanges (
  meetingid VARCHAR(255) NOT NULL,
  updated TIMESTAMP NULL DEFAULT NULL,
  updatedby VARCHAR(255) DEFAULT NULL,
  approved TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
  approvedby VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (meetingid)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table meetingday
--
CREATE TABLE meetingday (
  meetingdayindex INT(11) NOT NULL AUTO_INCREMENT,
  meetingday VARCHAR(255) DEFAULT NULL,
  updated TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updatedby INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (meetingdayindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 8
AVG_ROW_LENGTH = 2340
CHARACTER SET latin1
COLLATE latin1_swedish_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table meetingend
--
CREATE TABLE meetingend (
  meetingendindex INT(11) NOT NULL AUTO_INCREMENT,
  meetingend TEXT NOT NULL,
  updated TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updatedby INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (meetingendindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 49
AVG_ROW_LENGTH = 341
CHARACTER SET latin1
COLLATE latin1_swedish_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table meetingfrequency
--
CREATE TABLE meetingfrequency (
  meetingfrequencyindex INT(11) NOT NULL AUTO_INCREMENT,
  meetingfrequency VARCHAR(255) DEFAULT NULL,
  updated TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updatedby INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (meetingfrequencyindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 9
AVG_ROW_LENGTH = 3276
CHARACTER SET latin1
COLLATE latin1_swedish_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table meetinglegend
--
CREATE TABLE meetinglegend (
  meetinglegendindex INT(11) NOT NULL AUTO_INCREMENT,
  code VARCHAR(255) DEFAULT NULL,
  description VARCHAR(255) DEFAULT NULL,
  active BIT(1) DEFAULT NULL,
  updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedby INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (meetinglegendindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 25
AVG_ROW_LENGTH = 744
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table meetingprofile
--
CREATE TABLE meetingprofile (
  meetingprofileindex INT(11) NOT NULL AUTO_INCREMENT,
  meetingid INT(11) NOT NULL,
  legenditemid INT(11) NOT NULL,
  PRIMARY KEY (meetingprofileindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table meetings
--
CREATE TABLE meetings (
  meetingindex INT(11) NOT NULL AUTO_INCREMENT,
  groupid INT(11) DEFAULT NULL,
  active BIT(1) DEFAULT b'1',
  meetingname VARCHAR(255) DEFAULT NULL,
  meetinglocationid INT(11) NOT NULL DEFAULT 1,
  meetingdayid INT(11) DEFAULT NULL,
  meetingfrequencyid INT(11) NOT NULL DEFAULT 1,
  meetingstartid INT(11) DEFAULT NULL,
  meetingendid INT(11) DEFAULT NULL,
  updated TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updatedby INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (meetingindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table meetingstart
--
CREATE TABLE meetingstart (
  meetingstartindex INT(11) NOT NULL AUTO_INCREMENT,
  meetingstart VARCHAR(255) NOT NULL,
  updated TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updatedby INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (meetingstartindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 49
AVG_ROW_LENGTH = 341
CHARACTER SET latin1
COLLATE latin1_swedish_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table meetingtype
--
CREATE TABLE meetingtype (
  meetingtypeindex INT(11) NOT NULL AUTO_INCREMENT,
  meetingtype VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (meetingtypeindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 12
AVG_ROW_LENGTH = 1489
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table members
--
CREATE TABLE members (
  memberid INT(11) NOT NULL AUTO_INCREMENT,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,
  email VARCHAR(50) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  roleid INT(11) DEFAULT NULL,
  groupid INT(11) DEFAULT NULL,
  updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updatedby INT(11) NOT NULL DEFAULT 1,
  streetaddress VARCHAR(255) DEFAULT NULL,
  city VARCHAR(255) DEFAULT NULL,
  zipcode VARCHAR(255) DEFAULT NULL,
  phonenumber VARCHAR(255) DEFAULT NULL,
  adminlevelid INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (memberid)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table menwomen
--
CREATE TABLE menwomen (
  menwomenindex INT(11) NOT NULL AUTO_INCREMENT,
  typelong VARCHAR(255) DEFAULT NULL,
  typeletter VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (menwomenindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table openclosed
--
CREATE TABLE openclosed (
  openclosedindex VARCHAR(255) NOT NULL,
  typeletter VARCHAR(255) DEFAULT NULL,
  typeword VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (openclosedindex)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table orglevels
--
CREATE TABLE orglevels (
  orglevelsindex INT(11) NOT NULL AUTO_INCREMENT,
  orglevel VARCHAR(255) DEFAULT NULL,
  updated TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updatedby INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (orglevelsindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 8
AVG_ROW_LENGTH = 2730
CHARACTER SET latin1
COLLATE latin1_swedish_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table roles
--
CREATE TABLE roles (
  rolesindex INT(11) NOT NULL AUTO_INCREMENT,
  role VARCHAR(255) DEFAULT NULL,
  orglevel INT(11) DEFAULT NULL,
  updated TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updatedby INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (rolesindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 11
AVG_ROW_LENGTH = 1638
CHARACTER SET latin1
COLLATE latin1_swedish_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table rotations
--
CREATE TABLE rotations (
  rotationsindex INT(11) NOT NULL AUTO_INCREMENT,
  rotationname TEXT NOT NULL,
  rotationstart DATE NOT NULL,
  rotationend DATE NOT NULL,
  orglevel INT(11) NOT NULL,
  PRIMARY KEY (rotationsindex)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for view committeesvw
--
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW committeesvw
AS
SELECT
  `orglevels`.`orglevel` AS `orglevel`,
  `areas`.`areaname` AS `areaname`,
  `areas`.`areadescription` AS `areadescription`,
  `committees`.`committee` AS `committee`,
  `committees`.`committeedescription` AS `committeedescription`
FROM ((`committees`
  JOIN `orglevels`
    ON ((`committees`.`orglevelid` = `orglevels`.`orglevelsindex`)))
  JOIN `areas`
    ON ((`areas`.`areasindex` = `committees`.`areasindex`)))
ORDER BY `committees`.`committee`;

--
-- Definition for view meetingsview
--
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW meetingsview
AS
SELECT
  `meetings`.`meetingname` AS `meetingname`,
  `groups`.`groupname` AS `groupname`,
  `meetingday`.`meetingday` AS `meetingday`,
  `meetingfrequency`.`meetingfrequency` AS `meetingfrequency`,
  `meetingstart`.`meetingstart` AS `meetingstart`,
  `meetingend`.`meetingend` AS `meetingend`,
  `locations`.`locationname` AS `locationname`,
  `locationtypes`.`locationtype` AS `locationtype`,
  `locations`.`locationaddress` AS `locationaddress`,
  `locations`.`locationcity` AS `locationcity`,
  `locations`.`locationstate` AS `locationstate`,
  `locations`.`locationzip` AS `locationzip`,
  `districts`.`district` AS `district`,
  `districts`.`districtdescription` AS `districtdescription`,
  `areas`.`areaname` AS `areaname`,
  `areas`.`areadescription` AS `areadescription`,
  `locations`.`locationlat` AS `locationlat`,
  `locations`.`locationlng` AS `locationlng`
FROM (((((((((`groups`
  JOIN `meetings`
    ON ((`groups`.`groupsindex` = `meetings`.`groupid`)))
  JOIN `meetingday`
    ON ((`meetings`.`meetingdayid` = `meetingday`.`meetingdayindex`)))
  JOIN `meetingfrequency`
    ON ((`meetings`.`meetingfrequencyid` = `meetingfrequency`.`meetingfrequencyindex`)))
  JOIN `meetingstart`
    ON ((`meetings`.`meetingstartid` = `meetingstart`.`meetingstartindex`)))
  JOIN `districts`
    ON ((`groups`.`districtindex` = `districts`.`districtsindex`)))
  JOIN `areas`
    ON ((`districts`.`areaindex` = `areas`.`areasindex`)))
  JOIN `locations`
    ON ((`meetings`.`meetinglocationid` = `locations`.`locationsindex`)))
  JOIN `locationtypes`
    ON ((`locations`.`locationtypeid` = `locationtypes`.`locationtypesindex`)))
  JOIN `meetingend`
    ON ((`meetings`.`meetingendid` = `meetingend`.`meetingendindex`)))
WHERE (`meetings`.`active` = 1)
GROUP BY `locations`.`locationcity`,
         `locations`.`locationzip`,
         `meetingday`.`meetingday`,
         `meetingstart`.`meetingstart`,
         `locations`.`locationaddress`,
         `groups`.`groupname`,
         `meetings`.`meetingname`
ORDER BY `locations`.`locationcity`, `locations`.`locationzip`, `meetingday`.`meetingday`, `meetingstart`.`meetingstart`, `locations`.`locationaddress`, `groups`.`groupname`, `meetings`.`meetingname`;

--
-- Definition for view mtgprofilevw
--
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW mtgprofilevw
AS
SELECT
  `meetings`.`meetingname` AS `meetingname`,
  `meetinglegend`.`code` AS `code`,
  `meetinglegend`.`description` AS `description`
FROM ((`meetings`
  JOIN `meetingprofile`
    ON ((`meetings`.`meetingindex` = `meetingprofile`.`meetingid`)))
  JOIN `meetinglegend`
    ON ((`meetingprofile`.`legenditemid` = `meetinglegend`.`meetinglegendindex`)))
WHERE (`meetinglegend`.`active` = 1);

--
-- Definition for view `meetings with profile codes`
--
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW `meetings with profile codes`
AS
SELECT
  `mtgprofilevw`.`meetingname` AS `meetingname`,
  GROUP_CONCAT(`mtgprofilevw`.`code` SEPARATOR ', ') AS `GROUP_CONCAT(mtgprofilevw.code SEPARATOR ', ')`
FROM `mtgprofilevw`
GROUP BY `mtgprofilevw`.`meetingname`;

--
-- Definition for view meetingsummaryvw
--
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW meetingsummaryvw
AS
SELECT
  `meetingsview`.`meetingname` AS `meetingname`,
  `meetingsview`.`groupname` AS `groupname`,
  `meetingsview`.`meetingday` AS `meetingday`,
  `meetingsview`.`meetingfrequency` AS `meetingfrequency`,
  `meetings with profile codes`.`GROUP_CONCAT(mtgprofilevw.code SEPARATOR ', ')` AS `GROUP_CONCAT(mtgprofilevw.code SEPARATOR ', ')`
FROM (`meetingsview`
  JOIN `meetings with profile codes`
    ON ((`meetingsview`.`meetingname` = `meetings with profile codes`.`meetingname`)));

-- 
-- Dumping data for table adminlevel
--
INSERT INTO adminlevel VALUES
(1, 'User'),
(2, 'Super User'),
(3, 'District Administrator'),
(4, 'Area Administrator'),
(5, 'Area DataBase Adiminstrator');

-- 
-- Dumping data for table areas
--
INSERT INTO areas VALUES
(1, 'Area 72', 'Western Washington', '2016-05-08 20:51:57', 1);

-- 
-- Dumping data for table committeepositions
--

-- Table area72webdemo.committeepositions does not contain any data (it is empty)

-- 
-- Dumping data for table committees
--
INSERT INTO committees VALUES
(2, 'Accessibility Committee', 3, 'This committee will handle all accessibility needs and issues for Western Washington Area. Along with funding to attend Area Quarterlies and the Assembly, this position has additional funds to provide interpretation for Area events. ', NULL, '2016-05-09 16:47:48', 1, 1),
(3, 'Archives Standing Committee', 3, 'The committee consists of the Area Archivist, the Archives Steering Committee, the District and other A.A. archivists. The Area Archivist and the Archives Steering Committee represent the interests of the local Archivists to the Area Committee and to the Assembly, although only the Archivist is a member of the Area Committee.', NULL, '2016-05-09 16:48:11', 1, 1),
(4, 'Archives Steering Committee', 3, 'The Archives Steering Committee consists of six members, each serving a four-year term. In each odd-numbered year, three members will be replaced. This insures continuity of experience on the Steering Committee. The seventh member of the Steering Committee is the Area Archivist, who acts as chairperson of the committee.', NULL, '2016-05-09 16:48:28', 1, 1),
(5, 'Cooperation with the Professional Community Committee', 3, 'Cooperation with the Professional Community (C.P.C.) is A.A.''s official contact with members of the professional community. If you are sober and have a desire to serve, we need your help! ', NULL, '2016-05-09 16:48:36', 1, 1),
(6, 'Corrections Committee', 3, 'The Area 72 Corrections Committee has one purpose: To help A.A. members carry the message of Alcoholics Anonymous to the alcoholic who is confined in a correctional facility. If you are sober and have a desire to serve, we need your help!', NULL, '2016-05-09 16:48:48', 1, 1),
(7, 'Grapevine and Literature Committee', 3, 'The Grapevine and Literature Committee follows the guidelines as outlined in the Grapevine Workbook and in the Literature Committee Guidelines marked MG-9 from G.S.O.  Exists primarily to educate the fellowship about A.A. literature, related service material, and how to obtain it. Maintains a comprehensive literature display consisting of items from A.A.W.S., G.S.O., A.A. Grapevine, Inc., and other A.A.', NULL, '2016-05-09 16:49:05', 1, 1),
(8, 'Public Information Committee', 3, 'Public Information (P.I.) in Alcoholics Anonymous (A.A.) means carrying the message of recovery to the still suffering alcoholic by informing the general public about the A.A. program.  If you are sober and have a desire to serve, you can help! When they''ve had enough, we want A.A. to be there in the yellow pages, on the bus signs, etc. - and that''s Public Information.', NULL, '2016-05-09 16:49:21', 1, 1),
(9, 'Treatment Facilities Committee', 3, 'The Area 72 Treatment Facilities Committee has one purpose: To help A.A. members carry the message of Alcoholics Anonymous into Treatment Facilities, and help "Bridge the Gap" between Facilities and A.A.  If you are sober and have a desire to serve, we need your help!', NULL, '2016-05-09 16:49:34', 1, 1),
(10, 'Web Standing Committee', 3, 'Our mission is to promote unity through application of the Twelve Traditions while working with modern technology to carry the AA message to the alcoholic who still suffers. ', NULL, '2016-05-09 16:49:46', 1, 1),
(11, 'Web Steering Committee', 3, 'The Area Web Steering Committee is created per motion 04.2 which states:  "The Area Website Committee be composed of the appointed Area Webmaster, the appointed  Area Public Information Chair and a steering committee of three volunteers with a demonstrated interest in the Traditions, general service and/or Websites.  The Committee will maintain and further develop the area Website, following policies set forth by the original Website committee to ensure that the traditions are upheld."', NULL, '2016-05-09 16:50:09', 1, 1),
(32, 'Other Committee', 3, 'New?  Please ask to have it added to the list.', NULL, '2016-05-09 16:50:29', 1, 1);

-- 
-- Dumping data for table districts
--
INSERT INTO districts VALUES
(1, 'District 01', 'Spanish speaking region that encompasses all of Western Washington south of?Lynnwood.', 1, '2016-05-08 20:53:01', 1),
(2, 'District 02', 'Camano Island & Northwest Snohomish County: Stanwood, Arlington, Silvana', 1, '2016-05-08 20:53:03', 1),
(3, 'District 03', 'Southeast Snohomish County: Lake Stevens, Snohomish, Monroe, Sultan, Goldbar, Index', 1, '2016-05-08 20:53:04', 1),
(4, 'District 04', 'Skagit County: Burlington, Concrete, Mt. Vernon, Sedro Woolley', 1, '2016-05-08 20:53:05', 1),
(5, 'District 07', 'South Clark and Skamania Counties: South Vancouver Area, Camas, Washougal, Stevenson, Carson', 1, '2016-05-08 20:53:06', 1),
(6, 'District 08', 'Thurston & Mason Counties: Olympia, Shelton, Lacey, Tumwater, Hoodsport, Matlock, Rainier, Littlerock', 1, '2016-05-08 20:53:11', 1),
(7, 'District 09', 'Central Tacoma: Fircrest', 1, '2016-05-08 20:53:12', 1),
(8, 'District 10', 'Kitsap Peninsula: Silverdale, Bainbridge Island, Port Orchard, Poulsbo, Chico, Belfair, Olalla', 1, '2016-05-08 20:53:12', 1),
(9, 'District 11', 'Whatcom County', 1, '2016-05-08 20:53:13', 1),
(10, 'District 12', 'North and East Snohomish County: Everett, Marysville', 1, '2016-05-08 20:53:13', 1),
(11, 'District 14', 'West Seattle, White Center, Vashon Island', 1, '2016-05-08 20:53:14', 1),
(12, 'District 15', 'Downtown Seattle, West Capitol Hill', 1, '2016-05-08 20:53:14', 1),
(13, 'District 16', 'Northeast Seattle, University District', 1, '2016-05-08 20:53:14', 1),
(14, 'District 17', 'Northwest Seattle, Ballard', 1, '2016-05-08 20:53:15', 1),
(15, 'District 18', 'Renton, Kent, Tukwila', 1, '2016-05-08 20:53:15', 1),
(16, 'District 19', 'South Everett and Mukilteo', 1, '2016-05-08 20:53:15', 1),
(17, 'District 21', 'Grays Harbor and Willipa Harbor Areas: Aberdeen, Hoquiam, Montesano, Raymond', 1, '2016-05-08 20:53:16', 1),
(18, 'District 22', 'North Olympic Peninsula: Port Angeles, Forks, Joyce, Neah Bay, Clallam Bay', 1, '2016-05-08 20:53:16', 1),
(19, 'District 24', 'Southwest Snohomish County: Lynnwood, Edmonds', 1, '2016-05-08 20:53:17', 1),
(20, 'District 27', 'Cowlitz, Pacific and Wahkiakum Counties: Longview-Kelso Area, Long Beach Peninsula', 1, '2016-05-08 20:53:17', 1),
(21, 'District 28', 'Lewis County: Centralia / Chehalis Area', 1, '2016-05-08 20:53:17', 1),
(22, 'District 29', 'Puyallup, Eatonville, Orting Area', 1, '2016-05-08 20:53:18', 1),
(23, 'District 31', 'Burien, Des Moines, Tukwila, SeaTac, Normandy Park', 1, '2016-05-08 20:53:18', 1),
(24, 'District 32', 'Auburn, Federal Way', 1, '2016-05-08 20:53:18', 1),
(25, 'District 33', 'Maple Valley, Covington, Black Diamond, Hobart, Summit, and East Kent', 1, '2016-05-08 20:53:19', 1),
(26, 'District 34', 'Bellevue, Redmond, East Lake Sammamish, Mercer Island', 1, '2016-05-08 20:53:19', 1),
(27, 'District 35', 'Issaquah, South Sammamish Plateau', 1, '2016-05-08 20:53:19', 1),
(28, 'District 36', 'North East King County: Snoqualmie Valley, Duvall, North Bend, Carnation, Fall City, Preston, Snoqualmie Pass', 1, '2016-05-08 20:53:20', 1),
(29, 'District 37', 'North Clark County, North Skamania County, North Vancouver, Battleground, Woodland, Orchards', 1, '2016-05-08 20:53:20', 1),
(30, 'District 38', 'Kirkland', 1, '2016-05-08 20:53:20', 1),
(31, 'District 39', 'Bothel, Kenmore, and Woodinville', 1, '2016-05-08 20:53:21', 1),
(32, 'District 40', 'East-Central Seattle: East Capital Hill, Madrona, Madison Beach', 1, '2016-05-08 20:53:21', 1),
(33, 'District 41', 'North-Central Seattle: Queen Anne, Magnolia', 1, '2016-05-08 20:53:21', 1),
(34, 'District 42', 'Northwest Seattle, Shoreline, and Lake Forest Park', 1, '2016-05-08 20:53:22', 1),
(35, 'District 43', 'Peninsula cities: Burley, Fox Island, Gig Harbor, Home, Lakebay, Manchester, Olalla, Port Orchard, Retsil', 1, '2016-05-08 20:53:22', 1),
(36, 'District 44', 'North Tacoma', 1, '2016-05-08 20:53:23', 1),
(37, 'District 45', 'Southwest Pierce County: South Tacoma, Lakewood, Parkland, Spanaway, Steilacoom', 1, '2016-05-08 20:53:24', 1),
(38, 'District 46', 'Whidbey and San Juan Islands: Anacortes', 1, '2016-05-08 20:53:24', 1),
(39, 'District 54', 'Bonney Lake, Buckley, Carbonado, Enumclaw, and South Prairie', 1, '2016-05-08 20:53:25', 1),
(40, 'District 55', 'Sequim Area', 1, '2016-05-08 20:53:25', 1),
(41, 'District 56', 'East Jefferson County: Port Townsend, Quilcene, Brinnon, Port Hadlock, Chimacum, Coyle', 1, '2016-05-08 20:53:26', 1),
(42, 'District 57', 'Spanish speaking region that encompasses all of Western Washington from Lynnwood and to the north.', 1, '2016-05-08 20:53:26', 1);

-- 
-- Dumping data for table districtzipcodes
--

-- Table area72webdemo.districtzipcodes does not contain any data (it is empty)

-- 
-- Dumping data for table groups
--
INSERT INTO groups VALUES
(1, 'Silver Lake ', 16, '2016-05-08 21:22:53', 1, NULL);

-- 
-- Dumping data for table gsrbygroup
--
INSERT INTO gsrbygroup VALUES
(1, 1, 1, '2015-02-01 14:28:12', '2017-02-01', 'space for comments');

-- 
-- Dumping data for table locationcomments
--
INSERT INTO locationcomments VALUES
(1, 1, 'Meetings in Portable C', False);

-- 
-- Dumping data for table locationdetails
--

-- Table area72webdemo.locationdetails does not contain any data (it is empty)

-- 
-- Dumping data for table locations
--
INSERT INTO locations VALUES
(1, 'Advent Lutheran Church', '4306 132nd St SE, Mill Creek', 'Mill Creek', 'WA', 0, 1, NULL, NULL, '2016-05-09 13:17:38', 1);

-- 
-- Dumping data for table locationtypes
--
INSERT INTO locationtypes VALUES
(1, 'Chruch', '2016-05-08 21:08:08', 1),
(2, 'Hospital', '2016-05-08 21:08:13', 1),
(3, 'Treatment Center', '2016-05-08 21:08:20', 1),
(4, 'Corrections Facility', '2016-05-08 21:08:25', 1),
(5, 'Public Building', '2016-05-08 21:08:37', 1),
(6, 'Private Building', '2016-05-08 21:08:47', 1),
(7, 'Restaurant', '2016-05-08 21:08:55', 1),
(8, 'Outdoor', '2016-05-08 21:09:03', 1);

-- 
-- Dumping data for table meetingchanges
--

-- Table area72webdemo.meetingchanges does not contain any data (it is empty)

-- 
-- Dumping data for table meetingday
--
INSERT INTO meetingday VALUES
(1, 'Monday', '2016-05-08 21:09:19', 1),
(2, 'Tuesday', '2016-05-08 21:09:21', 1),
(3, 'Wednesday', '2016-05-08 21:09:25', 1),
(4, 'Thursday', '2016-05-08 21:09:29', 1),
(5, 'Friday', '2016-05-08 21:09:31', 1),
(6, 'Saturday', '2016-05-08 21:09:34', 1),
(7, 'Sunday', '2016-05-08 21:09:38', 1);

-- 
-- Dumping data for table meetingend
--
INSERT INTO meetingend VALUES
(1, '6:30 AM', '2016-05-08 20:43:08', 1),
(2, '7:00 AM', '2016-05-08 20:43:08', 1),
(3, '7:30 AM', '2016-05-08 20:43:08', 1),
(4, '8:00 AM', '2016-05-08 20:43:08', 1),
(5, '8:30 AM', '2016-05-08 20:43:08', 1),
(6, '9:00 AM', '2016-05-08 20:43:08', 1),
(7, '9:30 AM', '2016-05-08 20:43:08', 1),
(8, '10:00 AM', '2016-05-08 20:43:08', 1),
(9, '10:30 AM', '2016-05-08 20:43:08', 1),
(10, '11:00 AM', '2016-05-08 20:43:08', 1),
(11, '11:30 AM', '2016-05-08 20:43:08', 1),
(12, '12:00 PM', '2016-05-08 20:43:08', 1),
(13, '12:30 PM', '2016-05-08 20:43:08', 1),
(14, '1:00 PM', '2016-05-08 20:43:08', 1),
(15, '1:30 PM', '2016-05-08 20:43:08', 1),
(16, '2:00 PM', '2016-05-08 20:43:08', 1),
(17, '2:30 PM', '2016-05-08 20:43:08', 1),
(18, '3:00 PM', '2016-05-08 20:43:08', 1),
(19, '3:30 PM', '2016-05-08 20:43:08', 1),
(20, '4:00 PM', '2016-05-08 20:43:08', 1),
(21, '4:30 PM', '2016-05-08 20:43:08', 1),
(22, '5:00 PM', '2016-05-08 20:43:08', 1),
(23, '5:30 PM', '2016-05-08 20:43:08', 1),
(24, '6:00 PM', '2016-05-08 20:43:08', 1),
(25, '6:30 PM', '2016-05-08 20:43:08', 1),
(26, '7:00 PM', '2016-05-08 20:43:08', 1),
(27, '7:30 PM', '2016-05-08 20:43:08', 1),
(28, '8:00 PM', '2016-05-08 20:43:08', 1),
(29, '8:30 PM', '2016-05-08 20:43:08', 1),
(30, '9:00 PM', '2016-05-08 20:43:08', 1),
(31, '9:30 PM', '2016-05-08 20:43:08', 1),
(32, '10:00 PM', '2016-05-08 20:43:08', 1),
(33, '10:30 PM', '2016-05-08 20:43:08', 1),
(34, '11:00 PM', '2016-05-08 20:43:08', 1),
(35, '11:30 PM', '2016-05-08 20:43:08', 1),
(36, '12:00 AM', '2016-05-08 20:43:08', 1),
(37, '12:30 AM', '2016-05-08 20:43:08', 1),
(38, '1:00 AM', '2016-05-08 20:43:08', 1),
(39, '1:30 AM', '2016-05-08 20:43:08', 1),
(40, '2:00 AM', '2016-05-08 20:43:08', 1),
(41, '2:30 AM', '2016-05-08 20:43:08', 1),
(42, '3:00 AM', '2016-05-08 20:43:08', 1),
(43, '3:30 AM', '2016-05-08 20:43:08', 1),
(44, '4:00 AM', '2016-05-08 20:43:08', 1),
(45, '4:30 AM', '2016-05-08 20:43:08', 1),
(46, '5:00 AM', '2016-05-08 20:43:08', 1),
(47, '5:30 AM', '2016-05-08 20:43:08', 1),
(48, '6:00 AM', '2016-05-08 20:43:08', 1);

-- 
-- Dumping data for table meetingfrequency
--
INSERT INTO meetingfrequency VALUES
(1, 'Daily', '2016-05-08 20:03:08', 1),
(2, 'Weekly', '2016-05-08 20:03:08', 1),
(3, 'Monthly', '2016-05-08 20:03:08', 1),
(4, 'Quarterly', '2016-05-08 20:03:08', 1),
(5, 'Annually', '2016-05-08 20:03:08', 1),
(6, 'Once in a blue moon', '2016-05-09 17:38:07', 1),
(7, 'Never', '2016-05-09 17:38:10', 1),
(8, 'After having had a spirtutal awakening', '2016-05-09 17:38:28', 1);

-- 
-- Dumping data for table meetinglegend
--
INSERT INTO meetinglegend VALUES
(1, 'AN', 'Al-Anon meeting at same time and location', True, '2016-05-09 16:16:45', 1),
(2, 'AT', 'Alateen meeting at same time and location', True, '2016-05-09 16:16:45', 1),
(3, 'CC', 'Child care available at meeting', True, '2016-05-09 16:16:45', 1),
(4, 'GS', 'Gay/lesbian supported meeting', True, '2016-05-09 16:16:45', 1),
(5, 'MO', 'Men only', True, '2016-05-09 16:16:45', 1),
(6, '1H', 'One-hour meeting (all other meetings are 90 minutes)', True, '2016-05-09 16:16:45', 1),
(7, 'ASL', 'Sign interpreted for hearing impaired', True, '2016-05-09 16:16:45', 1),
(8, 'SP', 'Speaker meeting', True, '2016-05-09 16:16:45', 1),
(9, 'ES', 'Junta en Espanol', True, '2016-05-09 16:16:45', 1),
(10, 'WB', 'Wheelchair accessible bathrooms', True, '2016-05-09 16:16:45', 1),
(11, 'WE', 'Wheelchair accessible entrance', True, '2016-05-09 16:16:45', 1),
(12, 'WO', 'Women only', True, '2016-05-09 16:16:45', 1),
(13, 'WP', 'Wheelchair accessible parking', True, '2016-05-09 16:16:45', 1),
(14, 'YP', 'Young peoples meeting', True, '2016-05-09 16:16:45', 1),
(15, 'BB', 'Big Book Discussion', True, '2016-05-09 16:16:45', 1),
(16, '12T', '12 Tradition Study', True, '2016-05-09 17:30:11', 1),
(17, '12ST', '12 Steps & 12 Traditions Study', True, '2016-05-09 17:31:35', 1),
(18, 'ST', 'Step Study', True, '2016-05-09 17:31:47', 1),
(19, 'BEG', 'Beginner/Newcomer meeting', True, '2016-05-09 17:32:22', 1),
(20, 'LWS', 'Last week of month speaker', True, '2016-05-09 17:32:34', 1),
(21, 'FWS', 'First week of month speaker', True, '2016-05-09 17:32:48', 1),
(22, 'NCS', 'No court slip signed but all welcome', True, '2016-05-09 17:34:10', 1),
(23, 'CW', 'Attended children welcome.  No formal childcare.', True, '2016-05-09 17:36:58', 1),
(24, 'SS', 'Junta en Espanol', NULL, '2016-05-15 15:07:35', 1);

-- 
-- Dumping data for table meetingprofile
--
INSERT INTO meetingprofile VALUES
(1, 1, 6),
(2, 1, 10),
(3, 1, 11),
(4, 1, 23);

-- 
-- Dumping data for table meetings
--
INSERT INTO meetings VALUES
(1, 1, True, 'More Will Be Revealed', 1, 6, 2, 3, 4, '2016-05-09 13:37:23', 1);

-- 
-- Dumping data for table meetingstart
--
INSERT INTO meetingstart VALUES
(1, '6:00 AM', '2016-05-08 20:27:19', 1),
(2, '6:30 AM', '2016-05-08 20:27:19', 1),
(3, '7:00 AM', '2016-05-08 20:27:19', 1),
(4, '7:30 AM', '2016-05-08 20:27:19', 1),
(5, '8:00 AM', '2016-05-08 20:27:19', 1),
(6, '8:30 AM', '2016-05-08 20:27:19', 1),
(7, '9:00 AM', '2016-05-08 20:27:19', 1),
(8, '9:30 AM', '2016-05-08 20:27:19', 1),
(9, '10:00 AM', '2016-05-08 20:27:19', 1),
(10, '10:30 AM', '2016-05-08 20:27:19', 1),
(11, '11:00 AM', '2016-05-08 20:27:19', 1),
(12, '11:30 AM', '2016-05-08 20:27:19', 1),
(13, '12:00 PM', '2016-05-08 20:27:19', 1),
(14, '12:30 PM', '2016-05-08 20:27:19', 1),
(15, '1:00 PM', '2016-05-08 20:27:19', 1),
(16, '1:30 PM', '2016-05-08 20:27:19', 1),
(17, '2:00 PM', '2016-05-08 20:27:19', 1),
(18, '2:30 PM', '2016-05-08 20:27:19', 1),
(19, '3:00 PM', '2016-05-08 20:27:19', 1),
(20, '3:30 PM', '2016-05-08 20:27:19', 1),
(21, '4:00 PM', '2016-05-08 20:27:19', 1),
(22, '4:30 PM', '2016-05-08 20:27:19', 1),
(23, '5:00 PM', '2016-05-08 20:27:19', 1),
(24, '5:30 PM', '2016-05-08 20:27:19', 1),
(25, '6:00 PM', '2016-05-08 20:27:19', 1),
(26, '6:30 PM', '2016-05-08 20:27:19', 1),
(27, '7:00 PM', '2016-05-08 20:27:19', 1),
(28, '7:30 PM', '2016-05-08 20:27:19', 1),
(29, '8:00 PM', '2016-05-08 20:27:19', 1),
(30, '8:30 PM', '2016-05-08 20:27:19', 1),
(31, '9:00 PM', '2016-05-08 20:27:19', 1),
(32, '9:30 PM', '2016-05-08 20:27:19', 1),
(33, '10:00 PM', '2016-05-08 20:27:19', 1),
(34, '10:30 PM', '2016-05-08 20:27:19', 1),
(35, '11:00 PM', '2016-05-08 20:27:19', 1),
(36, '11:30 PM', '2016-05-08 20:27:19', 1),
(37, '12:00 AM', '2016-05-08 20:27:19', 1),
(38, '12:30 AM', '2016-05-08 20:27:19', 1),
(39, '1:00 AM', '2016-05-08 20:27:19', 1),
(40, '1:30 AM', '2016-05-08 20:27:19', 1),
(41, '2:00 AM', '2016-05-08 20:27:19', 1),
(42, '2:30 AM', '2016-05-08 20:27:19', 1),
(43, '3:00 AM', '2016-05-08 20:27:19', 1),
(44, '3:30 AM', '2016-05-08 20:27:19', 1),
(45, '4:00 AM', '2016-05-08 20:27:19', 1),
(46, '4:30 AM', '2016-05-08 20:27:19', 1),
(47, '5:00 AM', '2016-05-08 20:27:19', 1),
(48, '5:30 AM', '2016-05-08 20:27:19', 1);

-- 
-- Dumping data for table meetingtype
--
INSERT INTO meetingtype VALUES
(1, 'Group meeting'),
(2, 'District Business Meeting'),
(3, 'Area Business Meeting'),
(4, 'Pre-Assembly'),
(5, 'Pre-Conference'),
(6, 'Area Assembly'),
(7, 'Area Conference'),
(8, 'District Committee Meeting'),
(9, 'Area Committee Meeting'),
(10, 'Group Business Meeting'),
(11, NULL);

-- 
-- Dumping data for table members
--
INSERT INTO members VALUES
(1, 'Ian', 'Melanson', 'igmelanson@gmail.com', 'password', 2, 1, '2016-05-08 21:20:33', 1, NULL, NULL, NULL, NULL, 1);

-- 
-- Dumping data for table menwomen
--

-- Table area72webdemo.menwomen does not contain any data (it is empty)

-- 
-- Dumping data for table openclosed
--

-- Table area72webdemo.openclosed does not contain any data (it is empty)

-- 
-- Dumping data for table orglevels
--
INSERT INTO orglevels VALUES
(1, 'Group', '2016-05-08 21:02:43', 1),
(2, 'District', '2016-05-08 21:02:52', 1),
(3, 'Area', '2016-05-08 21:02:57', 1),
(4, 'General Service Office', '2016-05-08 21:03:09', 1),
(5, 'General Service Board', '2016-05-08 21:03:19', 1),
(6, 'Alcoholics Anonymous', '2016-05-08 21:20:06', 1),
(7, 'Other', '2016-05-09 17:25:19', 1);

-- 
-- Dumping data for table roles
--
INSERT INTO roles VALUES
(1, 'AA Member', 6, '2016-05-08 21:11:14', 1),
(2, 'General Service Representative', 1, '2016-05-09 13:59:16', 1),
(4, 'District Committee Chair', 2, '2016-05-08 21:12:18', 1),
(5, 'District Comittee Member', 2, '2016-05-08 21:12:49', 1),
(7, 'Delegate', 3, '2016-05-08 21:13:48', 1),
(8, 'Past Delegate', 3, '2016-05-08 21:14:24', 1),
(9, 'General Service Office', 4, '2016-05-08 21:17:06', 1),
(10, 'General Service Board', 5, '2016-05-08 21:15:15', 1);

-- 
-- Dumping data for table rotations
--

-- Table area72webdemo.rotations does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;